export interface CorpusCompany {
  name: string;
  sector: string;
  workflowCategory: string;
  stage: string;
  geography: string;
  website: string;
  description: string;
  profile: {
    problem: string;
    customer: string;
    aiUseCase: string;
    dataMoatPotential: string;
    businessModel: string;
    fundingStage: string;
    competitiveLandscape: string;
    risks: string[];
  };
}

export interface Corpus {
  id: string;
  label: string;
  description: string;
  companies: CorpusCompany[];
}

const Q1_2026: CorpusCompany[] = [
  {
    name: 'Abridge',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Documentation',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.abridge.com',
    description: 'Abridge captures and structures clinician-patient conversations using audio AI to generate clinical notes and reduce physician documentation burden.',
    profile: {
      problem: 'Physicians spend 2+ hours daily on EHR documentation, driving burnout and reducing face-time with patients.',
      customer: 'Health systems and large medical groups deploying ambient AI scribes to clinicians.',
      aiUseCase: 'Real-time speech-to-text plus medical LLM that converts conversations into structured SOAP notes and discrete EHR data.',
      dataMoatPotential: 'High — proprietary clinician-patient audio corpus and edits-as-labels create a self-improving model unique to medical conversation.',
      businessModel: 'Per-clinician monthly subscription with enterprise contracts.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Nuance DAX, Suki, Nabla, and Heidi Health.',
      risks: ['Heavy EHR integration burden', 'Highly competitive ambient scribe category', 'Clinical accuracy expectations leave little margin for error'],
    },
  },
  {
    name: 'Hippocratic AI',
    sector: 'Healthcare',
    workflowCategory: 'Patient Engagement',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.hippocraticai.com',
    description: 'Hippocratic AI builds safety-focused healthcare LLMs that power agentic phone agents for non-diagnostic patient outreach like pre-op and post-discharge.',
    profile: {
      problem: 'Healthcare staffing shortages mean millions of patient outreach calls — appointment prep, medication adherence, post-discharge check-ins — go unmade.',
      customer: 'Payers, large health systems, and pharmacy benefit managers.',
      aiUseCase: 'Voice-based generative AI nurses that conduct structured, scripted clinical outreach with a safety supervisor model in the loop.',
      dataMoatPotential: 'Medium-High — proprietary safety evals and clinical conversation datasets, but model training stack is increasingly commodified.',
      businessModel: 'Per-call or per-completed-outreach pricing with enterprise contracts.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Memora Health, Notable, and traditional IVR vendors.',
      risks: ['Regulatory uncertainty around AI in clinical workflows', 'Phone-based outreach has declining engagement vs. text', 'Trust dependent on never-causing-harm guarantees'],
    },
  },
  {
    name: 'Cohere Health',
    sector: 'Healthcare',
    workflowCategory: 'Prior Auth',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.coherehealth.com',
    description: 'Cohere Health automates prior authorization end-to-end for payers and providers using AI to interpret clinical guidelines and submit decisions.',
    profile: {
      problem: 'Prior authorization adds friction, delays care, and costs payers and providers billions annually in manual review labor.',
      customer: 'Health plans (especially Medicare Advantage) and large specialty practices.',
      aiUseCase: 'AI agent that ingests clinical documentation, maps to payer-specific medical policy, and issues real-time PA decisions with audit trails.',
      dataMoatPotential: 'High — clinical-criteria mapping and payer policy interpretation models that improve with every decision.',
      businessModel: 'Per-authorization pricing plus payer enterprise SaaS.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Olive (defunct), Rhyme, and incumbent UM vendors like Change Healthcare.',
      risks: ['Long sales cycles into health plans', 'New federal PA rules may compress pricing', 'Requires deep clinical and regulatory expertise'],
    },
  },
  {
    name: 'Owkin',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Series B',
    geography: 'France / United States',
    website: 'https://www.owkin.com',
    description: 'Owkin partners with hospitals on federated learning across pathology and multi-omic data to identify drug targets and patient subgroups for clinical trials.',
    profile: {
      problem: 'Drug developers lack access to high-quality, IRB-cleared real-world data across hospitals — slowing target identification and trial design.',
      customer: 'Top-20 pharma and large biotech R&D groups.',
      aiUseCase: 'Federated learning across hospital data silos plus AI models for pathology, biomarker discovery, and trial cohort selection.',
      dataMoatPotential: 'High — exclusive hospital data partnerships and federated infrastructure are difficult to replicate.',
      businessModel: 'Pharma partnership deals plus royalties on co-discovered assets.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Tempus, Flatiron Health, and academic data consortia.',
      risks: ['Federated learning operational complexity', 'Pharma sales cycles 12-18 months', 'Heavy dependence on a small number of large contracts'],
    },
  },
  {
    name: 'Sardine',
    sector: 'Financial Services',
    workflowCategory: 'Fraud',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.sardine.ai',
    description: 'Sardine is a behavioral-biometrics and ML-driven platform for fraud, compliance, and AML risk decisioning across banks, fintechs, and crypto.',
    profile: {
      problem: 'Fintechs and banks lose billions to account-takeover, money-laundering, and synthetic-identity fraud — point tools miss cross-cutting behavioral signals.',
      customer: 'Fintechs, neobanks, crypto exchanges, and mid-size banks.',
      aiUseCase: 'Behavioral biometrics, device intelligence, and ML risk models combined with rules and case management tooling.',
      dataMoatPotential: 'High — pooled fraud signal across customers compounds detection accuracy.',
      businessModel: 'Per-transaction pricing plus platform subscription.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Alloy, Unit21, Socure, and incumbent vendors like LexisNexis.',
      risks: ['Highly competitive risk and fraud category', 'Heavy reliance on data partnerships', 'Crypto exposure creates revenue volatility'],
    },
  },
  {
    name: 'Eko Health',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Decision Support',
    stage: 'Series D',
    geography: 'United States',
    website: 'https://www.ekohealth.com',
    description: 'Eko combines AI-enabled digital stethoscopes and ECG hardware with FDA-cleared algorithms for detecting heart murmurs and atrial fibrillation.',
    profile: {
      problem: 'Primary care clinicians miss early signals of structural heart disease and arrhythmia, leading to late-stage diagnoses and avoidable hospitalizations.',
      customer: 'Primary care clinics, telehealth providers, and pediatric practices.',
      aiUseCase: 'FDA-cleared deep learning on heart sound and ECG signals for early disease screening at point of care.',
      dataMoatPotential: 'High — proprietary heart sound dataset and FDA-cleared algorithms create regulatory and data moats.',
      businessModel: 'Hardware sales plus per-clinician AI subscription.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Competes with traditional stethoscope incumbents (3M Littmann) and ECG vendors (AliveCor).',
      risks: ['Hardware-software business has lower gross margins than pure SaaS', 'Reimbursement codes still maturing for AI screening', 'Sales motion into primary care is fragmented'],
    },
  },
  {
    name: 'Insilico Medicine',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Series E',
    geography: 'Hong Kong / United States',
    website: 'https://insilico.com',
    description: 'Insilico Medicine uses generative AI for end-to-end drug discovery — target identification, molecule design, and clinical trial design — with multiple internal pipeline assets.',
    profile: {
      problem: 'Traditional drug discovery takes 10+ years and >$2B per approved drug, with >90% clinical failure rates.',
      customer: 'Big pharma partners and internal pipeline development for own clinical-stage assets.',
      aiUseCase: 'Generative chemistry, AI target identification, and AI clinical trial design integrated into an end-to-end discovery platform.',
      dataMoatPotential: 'High — large proprietary chemistry datasets and platform integration across the discovery cascade.',
      businessModel: 'Pharma partnership upfronts + milestones plus internal pipeline development.',
      fundingStage: 'Series E (pre-IPO)',
      competitiveLandscape: 'Competes with Recursion, BenevolentAI, Schrödinger, and Isomorphic Labs.',
      risks: ['Clinical validation still in progress for AI-discovered assets', 'Capital-intensive pipeline development', 'Geopolitical exposure given Hong Kong / China operations'],
    },
  },
  {
    name: 'Alloy',
    sector: 'Financial Services',
    workflowCategory: 'KYC',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.alloy.com',
    description: 'Alloy provides an identity decisioning platform for KYC/AML, fraud, and credit decisions used by hundreds of banks and fintechs.',
    profile: {
      problem: 'Banks and fintechs juggle dozens of identity, fraud, and credit data vendors with brittle in-house orchestration.',
      customer: 'Banks, credit unions, neobanks, and lenders.',
      aiUseCase: 'Decisioning orchestration layer plus ML-driven risk scoring across pooled identity and fraud signals.',
      dataMoatPotential: 'Medium-High — orchestration network effects and customer-specific decisioning rules increase switching costs.',
      businessModel: 'Per-decision and platform subscription pricing.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Persona, Socure, Unit21, and Sardine.',
      risks: ['Margin compression from upstream data vendors', 'Customer concentration risk among large fintechs', 'AML enforcement landscape evolving rapidly'],
    },
  },
  {
    name: 'Tennr',
    sector: 'Healthcare',
    workflowCategory: 'Referral Intake',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.tennr.com',
    description: 'Tennr automates patient referral intake — parsing faxed and emailed referrals, extracting structured data, and routing them into specialty practice workflows.',
    profile: {
      problem: 'Specialty practices receive thousands of unstructured faxes and emails per week; manual triage drives delays, lost referrals, and revenue leakage.',
      customer: 'Multi-location specialty practices (orthopedics, GI, cardiology, pulmonology).',
      aiUseCase: 'OCR plus medical LLM that parses inbound documents, classifies referrals, extracts insurance and clinical data, and routes downstream.',
      dataMoatPotential: 'Medium-High — repeated parsing of specialty-specific document types creates accuracy advantages.',
      businessModel: 'Per-location SaaS subscription with usage-based add-ons.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with traditional fax/intake workflow tools and emerging AI fax startups.',
      risks: ['Fax remains the workflow but is in slow decline', 'Specialty market is fragmented', 'Customer concentration if a few large groups dominate revenue'],
    },
  },
  {
    name: 'OpenEvidence',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Decision Support',
    stage: 'Series A',
    geography: 'United States',
    website: 'https://www.openevidence.com',
    description: 'OpenEvidence is a clinician-facing answer engine that synthesizes peer-reviewed medical literature into evidence-based recommendations at the point of care.',
    profile: {
      problem: 'Physicians struggle to keep up with the medical literature firehose and lack fast, authoritative answers at the bedside.',
      customer: 'Practicing physicians, residents, and health systems licensing for enterprise use.',
      aiUseCase: 'Retrieval-augmented LLM grounded in indexed peer-reviewed literature with citation transparency.',
      dataMoatPotential: 'Medium — quality of indexed literature corpus and clinician feedback loop, but content licensing is partially commoditized.',
      businessModel: 'Free clinician tier plus enterprise health system licensing.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with UpToDate, DynaMed, and emerging clinician LLM tools.',
      risks: ['Hallucination risk in clinical recommendations', 'Established incumbents with EHR integration', 'Content licensing costs may rise'],
    },
  },
  {
    name: 'Trullion',
    sector: 'Financial Services',
    workflowCategory: 'Audit',
    stage: 'Series A',
    geography: 'United States / Israel',
    website: 'https://trullion.com',
    description: 'Trullion automates audit and revenue assurance workflows for accounting teams using AI to extract data from contracts and reconcile to financial systems.',
    profile: {
      problem: 'Accounting teams spend weeks reconciling contracts, lease data, and revenue schedules to ERP systems — work that is highly manual and error-prone.',
      customer: 'Mid-market finance and accounting teams and audit firms supporting them.',
      aiUseCase: 'Document AI for contracts and supporting docs, automated reconciliation, and AI-assisted audit workpaper generation.',
      dataMoatPotential: 'Medium — accuracy on standard accounting documents improves with volume but is not strongly proprietary.',
      businessModel: 'Annual SaaS subscription tiered by company size.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with FloQast, BlackLine (incumbent), and AuditBoard.',
      risks: ['Crowded accounting automation market', 'Incumbent ERP vendors building in AI features', 'Long mid-market sales cycles'],
    },
  },
  {
    name: 'Notable Health',
    sector: 'Healthcare',
    workflowCategory: 'Patient Engagement',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.notablehealth.com',
    description: 'Notable automates patient-facing workflows like intake, scheduling, and pre-visit prep using a workflow platform plus generative AI agents.',
    profile: {
      problem: 'Health systems run dozens of staff-heavy patient outreach workflows — intake forms, registration, pre-visit reminders — that scale poorly.',
      customer: 'Mid-to-large health systems and multi-specialty medical groups.',
      aiUseCase: 'Agentic AI workflows for patient outreach, intake, scheduling, and clinical coordination.',
      dataMoatPotential: 'Medium — playbook library and EHR-deep integrations create switching costs but are replicable over time.',
      businessModel: 'Per-clinician or per-encounter SaaS subscription.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Phreesia, Relatient, and EHR-native workflow tools (Epic MyChart).',
      risks: ['Epic and other EHRs adding overlapping native features', 'Health system sales cycles', 'Integration breadth required to compete'],
    },
  },
  {
    name: 'Recursion Pharmaceuticals',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Public',
    geography: 'United States',
    website: 'https://www.recursion.com',
    description: 'Recursion operates a high-throughput biology and computer vision platform that maps cell biology at scale to discover drug candidates across therapeutic areas.',
    profile: {
      problem: 'Drug discovery is bottlenecked by limited biological insight at scale; most experiments cannot connect compound to function across the cell-state space.',
      customer: 'Big pharma partners and own internal pipeline.',
      aiUseCase: 'Computer vision + ML over a proprietary high-content cellular imaging dataset (the Recursion OS) to identify drug candidates.',
      dataMoatPotential: 'High — proprietary multi-petabyte cellular imaging dataset is structurally hard to replicate.',
      businessModel: 'Pharma partnerships plus internal clinical pipeline value capture.',
      fundingStage: 'Public (NASDAQ: RXRX)',
      competitiveLandscape: 'Competes with Insilico, Isomorphic Labs, Schrödinger, and BenevolentAI.',
      risks: ['Public company with large cash burn', 'Pipeline assets still proving out clinically', 'Public market volatility for AI biotech'],
    },
  },
  {
    name: 'Hyro',
    sector: 'Healthcare',
    workflowCategory: 'Patient Engagement',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.hyro.ai',
    description: 'Hyro provides conversational AI assistants for healthcare call centers and patient access, automating routine inquiries and routing complex cases to humans.',
    profile: {
      problem: 'Healthcare call centers handle massive call volume for scheduling, billing, and basic clinical questions — driving labor cost and wait times.',
      customer: 'Health system contact centers and patient access teams.',
      aiUseCase: 'Conversational AI for voice and chat, integrated with health system source systems for scheduling, FAQs, and triage.',
      dataMoatPotential: 'Medium — health-system-specific intents and integration depth create switching costs.',
      businessModel: 'Enterprise SaaS subscription plus per-interaction pricing.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with traditional contact center AI vendors and emerging healthcare-specific agentic startups.',
      risks: ['LLM-based assistants commoditizing the category', 'Health system procurement is slow', 'Outcome measurement (deflection rate, CSAT) is contested'],
    },
  },
  {
    name: 'PathAI',
    sector: 'Life Sciences',
    workflowCategory: 'Diagnostics',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.pathai.com',
    description: 'PathAI builds AI-powered pathology tools for cancer diagnosis, biomarker development, and pharma R&D partnerships.',
    profile: {
      problem: 'Pathology is a critical bottleneck in oncology diagnosis and pharma trials, with high variability and slow turnaround.',
      customer: 'Reference labs, hospitals, and pharma R&D partners.',
      aiUseCase: 'Computer vision on histopathology whole slide images for diagnostic assist and pharma biomarker discovery.',
      dataMoatPotential: 'High — proprietary annotated pathology dataset and FDA-regulated algorithms are hard to replicate.',
      businessModel: 'Per-slide reading fees plus pharma R&D services contracts.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Paige.AI, Tempus, and large reference lab AI initiatives.',
      risks: ['Reimbursement for AI pathology still maturing', 'Heavy regulatory burden for diagnostic claims', 'Slow lab procurement cycles'],
    },
  },
  {
    name: 'Greenlite',
    sector: 'Financial Services',
    workflowCategory: 'Compliance',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.greenlite.ai',
    description: 'Greenlite automates BSA/AML and KYC compliance investigations using AI agents that gather evidence, summarize findings, and draft Suspicious Activity Reports.',
    profile: {
      problem: 'BSA officers at banks and fintechs spend most of their time on case investigation paperwork rather than judgment — driving compliance team burnout and SAR backlogs.',
      customer: 'Fintech BSA / financial crimes teams and community bank compliance shops.',
      aiUseCase: 'AI agent that pulls case data, cross-references sanctions and adverse media, drafts narrative summaries, and generates SAR drafts for analyst review.',
      dataMoatPotential: 'Medium — workflow-specific prompts and customer-tuned SAR templates create initial switching costs.',
      businessModel: 'Per-case pricing plus annual platform subscription.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with Hummingbird, Unit21, and incumbent case management vendors.',
      risks: ['Heavy regulatory scrutiny of AI in AML decisioning', 'Small ICP early on (fintech BSA teams)', 'Documentation quality variance'],
    },
  },
  {
    name: 'Aidoc',
    sector: 'Healthcare',
    workflowCategory: 'Diagnostics',
    stage: 'Series D',
    geography: 'Israel / United States',
    website: 'https://www.aidoc.com',
    description: 'Aidoc provides FDA-cleared AI for radiology to flag urgent findings (e.g. PE, intracranial hemorrhage, c-spine fractures) and orchestrate downstream clinical workflows.',
    profile: {
      problem: 'Critical radiology findings can be delayed for hours in busy hospitals, worsening patient outcomes especially in stroke and pulmonary embolism.',
      customer: 'Hospital radiology and emergency departments.',
      aiUseCase: 'FDA-cleared CV models triaging CT scans for time-critical findings, plus orchestration of downstream care team workflows.',
      dataMoatPotential: 'High — broad FDA-cleared portfolio and PACS-integrated workflow orchestration create entrenched workflows.',
      businessModel: 'Per-bed or per-scan enterprise subscription.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Competes with Viz.ai, RapidAI, and emerging radiology AI vendors.',
      risks: ['Reimbursement and ROI proof at scale', 'Slow PACS integration cycles', 'Radiology reimbursement pressure'],
    },
  },
  {
    name: 'Lendflow',
    sector: 'Financial Services',
    workflowCategory: 'Underwriting',
    stage: 'Series A',
    geography: 'United States',
    website: 'https://www.lendflow.com',
    description: 'Lendflow gives lenders an embedded decisioning platform that uses alternative data and ML to underwrite SMB loans.',
    profile: {
      problem: 'SMB lenders rely on slow, narrow underwriting that misses creditworthy small businesses lacking traditional credit data.',
      customer: 'Banks, fintechs, and software platforms originating SMB loans.',
      aiUseCase: 'ML-driven SMB credit decisioning using bank transaction data, accounting integrations, and alternative data signals.',
      dataMoatPotential: 'Medium — pooled SMB underwriting outcomes create defensible accuracy over time.',
      businessModel: 'Per-application pricing plus revenue share with embedded partners.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with Plaid Credit, Upstart, and OnDeck-style data partners.',
      risks: ['SMB credit risk highly correlated with macro cycle', 'Loan losses concentrated when underwriting is wrong', 'Data partner dependencies'],
    },
  },
];

const Q2_2026: CorpusCompany[] = [
  {
    name: 'Tempus AI',
    sector: 'Life Sciences',
    workflowCategory: 'Diagnostics',
    stage: 'Public',
    geography: 'United States',
    website: 'https://www.tempus.com',
    description: 'Tempus is a precision medicine company combining genomic sequencing, clinical data aggregation, and AI to support oncology decision-making and pharma R&D.',
    profile: {
      problem: 'Oncology decisions rely on fragmented clinical and genomic data; pharma also lacks scalable real-world data for biomarker discovery.',
      customer: 'Hospitals, oncology practices, and pharma R&D partners.',
      aiUseCase: 'AI over a massive aggregated dataset of de-identified clinical and genomic records for clinical decision support and biomarker discovery.',
      dataMoatPotential: 'High — multi-million patient longitudinal clinical-genomic dataset is structurally hard to replicate.',
      businessModel: 'Diagnostic test fees plus pharma R&D contracts and data licensing.',
      fundingStage: 'Public (NASDAQ: TEM)',
      competitiveLandscape: 'Competes with Foundation Medicine, Guardant Health, and clinical genomics incumbents.',
      risks: ['Reimbursement environment for genomic tests is uncertain', 'Public market scrutiny of margins and burn', 'Heavy capital intensity'],
    },
  },
  {
    name: 'Suki AI',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Documentation',
    stage: 'Series D',
    geography: 'United States',
    website: 'https://www.suki.ai',
    description: 'Suki AI is an ambient and assistive clinical voice assistant that helps physicians document notes, place orders, and interact with EHRs by voice.',
    profile: {
      problem: 'EHR documentation drives physician burnout; ambient AI scribes are emerging as the antidote.',
      customer: 'Health systems and medical groups deploying ambient scribes.',
      aiUseCase: 'Voice + LLM stack producing structured EHR notes from ambient conversation.',
      dataMoatPotential: 'Medium-High — clinician edit data and EHR integrations create switching costs.',
      businessModel: 'Per-clinician subscription with enterprise contracts.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Competes with Abridge, Nuance DAX, Heidi, and Nabla.',
      risks: ['Intense competition in ambient scribe', 'EHR vendor consolidation', 'Clinical accuracy bar is high'],
    },
  },
  {
    name: 'BioReason',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.bioreason.com',
    description: 'BioReason builds reasoning agents for biotech R&D — synthesizing literature, designing experiments, and interpreting results across multi-omic datasets.',
    profile: {
      problem: 'Biotech R&D teams cannot keep up with literature, multi-omic data, and experiment design — slowing target identification.',
      customer: 'Mid-size biotech R&D teams and pharma exploratory research groups.',
      aiUseCase: 'Agentic reasoning over scientific literature and proprietary biology datasets to propose experiments and interpret outcomes.',
      dataMoatPotential: 'Medium — workflow tooling and customer-specific corpora create switching costs.',
      businessModel: 'Per-seat SaaS plus pharma partnership contracts.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with broader pharma AI platforms and internal bioinformatics tools.',
      risks: ['LLM hallucination risk in scientific reasoning', 'Long sales into pharma', 'Bench scientist adoption hurdles'],
    },
  },
  {
    name: 'Unit21',
    sector: 'Financial Services',
    workflowCategory: 'Fraud',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.unit21.ai',
    description: 'Unit21 is a no-code risk and compliance platform for fintechs and banks, combining ML risk models with case management and SAR filing.',
    profile: {
      problem: 'Fintechs and banks juggle fragmented fraud, AML, and compliance tools; rules and ML need to live alongside investigator workflows.',
      customer: 'Fintechs, neobanks, payment processors, and mid-size banks.',
      aiUseCase: 'No-code rules + ML risk decisioning combined with case management and regulatory filing tooling.',
      dataMoatPotential: 'Medium-High — investigator workflow data and customer-tuned rules create lock-in.',
      businessModel: 'Per-transaction and platform pricing.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Sardine, Alloy, Hummingbird, and Persona.',
      risks: ['Highly competitive risk-platform space', 'AML enforcement landscape volatile', 'Reliance on fintech customer base subject to macro pressure'],
    },
  },
  {
    name: 'Glean',
    sector: 'Cross-Sector',
    workflowCategory: 'Knowledge Management',
    stage: 'Series E',
    geography: 'United States',
    website: 'https://www.glean.com',
    description: 'Glean provides enterprise AI search and assistants connecting to internal SaaS apps, enabling employees to find information and automate work.',
    profile: {
      problem: 'Knowledge workers waste hours searching across SaaS tools; LLMs cannot reason about internal company data without secure connectors.',
      customer: 'Mid-to-large enterprises across technology, financial services, and life sciences.',
      aiUseCase: 'Enterprise RAG plus agentic workflows over permissioned internal data sources.',
      dataMoatPotential: 'Medium — breadth of connectors and permission engine create switching costs.',
      businessModel: 'Per-seat enterprise SaaS.',
      fundingStage: 'Series E (late-stage)',
      competitiveLandscape: 'Competes with Microsoft Copilot, Google Agentspace, Notion AI.',
      risks: ['Hyperscaler competition (MSFT, GOOG) bundles into productivity suites', 'Permission and security complexity', 'Late-stage valuation pressure'],
    },
  },
  {
    name: 'Devoted Health',
    sector: 'Healthcare',
    workflowCategory: 'Payer Operations',
    stage: 'Private (Late)',
    geography: 'United States',
    website: 'https://www.devoted.com',
    description: 'Devoted Health is a tech-enabled Medicare Advantage plan with proprietary clinical and operational tooling — increasingly AI-enabled.',
    profile: {
      problem: 'Traditional Medicare Advantage plans run on legacy infrastructure with poor clinical engagement; tech-enabled payers can deliver better outcomes per dollar.',
      customer: 'Medicare Advantage members and provider network partners.',
      aiUseCase: 'AI for clinical risk stratification, member engagement, and operational automation across payer-provider workflows.',
      dataMoatPotential: 'High — full-stack payer-provider data and proprietary clinical model.',
      businessModel: 'Medicare Advantage premium revenue plus shared savings.',
      fundingStage: 'Private late-stage (>$1B raised)',
      competitiveLandscape: 'Competes with Humana, UnitedHealth, Clover Health, Bright Health (defunct).',
      risks: ['CMS rate pressure on MA', 'High medical loss ratio sensitivity', 'Path to profitability still pending'],
    },
  },
  {
    name: 'Iambic Therapeutics',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.iambic.com',
    description: 'Iambic Therapeutics integrates generative chemistry, deep learning, and automated wet lab science for drug discovery, with clinical-stage oncology assets.',
    profile: {
      problem: 'Generative drug discovery requires tight integration of AI prediction with wet lab feedback to actually deliver molecules.',
      customer: 'Internal pipeline development plus pharma partnerships.',
      aiUseCase: 'Generative chemistry + ADMET prediction tightly coupled to automated wet lab to close the discovery loop.',
      dataMoatPotential: 'High — proprietary tightly-coupled AI/wet-lab data flywheel.',
      businessModel: 'Internal pipeline value capture plus selective pharma partnerships.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Insilico, Recursion, Isomorphic Labs, Schrödinger.',
      risks: ['Clinical asset risk', 'Capital intensity of internal pipeline', 'Competitive AI drug discovery field'],
    },
  },
  {
    name: 'Persona',
    sector: 'Financial Services',
    workflowCategory: 'KYC',
    stage: 'Series D',
    geography: 'United States',
    website: 'https://www.withpersona.com',
    description: 'Persona is an identity infrastructure platform combining KYC/KYB verification, fraud signals, and decisioning across consumer and SMB onboarding.',
    profile: {
      problem: 'Companies need a flexible identity layer that adapts to consumer, marketplace, SMB, and gig identity flows — not point KYC tools.',
      customer: 'Fintechs, marketplaces, gig platforms, and SaaS vendors with onboarding.',
      aiUseCase: 'ML risk scoring plus orchestration over identity, fraud, and KYC data with developer-friendly APIs.',
      dataMoatPotential: 'High — orchestration breadth plus pooled fraud signal create network effects.',
      businessModel: 'Per-verification and platform pricing.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Competes with Alloy, Sardine, Stripe Identity, Socure.',
      risks: ['Stripe and other platform vendors bundling identity', 'Margin compression on KYC data vendors', 'Customer concentration risk'],
    },
  },
  {
    name: 'Pieces Technologies',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Documentation',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.piecestech.com',
    description: 'Pieces builds AI for inpatient clinical operations — discharge summaries, real-time clinical summarization, and quality measure capture.',
    profile: {
      problem: 'Inpatient care teams hand-write discharge summaries, status updates, and quality measure documentation, slowing throughput.',
      customer: 'Hospitals, especially Epic-integrated health systems.',
      aiUseCase: 'Inpatient-focused LLM workflows for discharge summary drafting, in-stay summarization, and quality measure extraction.',
      dataMoatPotential: 'Medium-High — inpatient-specific data and Epic integration depth.',
      businessModel: 'Per-bed or per-encounter enterprise SaaS.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Abridge (expanding into inpatient), Microsoft DAX inpatient, and internal Epic AI.',
      risks: ['Epic native AI tools threaten standalone vendors', 'Inpatient workflows are highly heterogeneous', 'Hospital sales cycles'],
    },
  },
  {
    name: 'Modern Treasury',
    sector: 'Financial Services',
    workflowCategory: 'Payments Operations',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.moderntreasury.com',
    description: 'Modern Treasury provides payments operations and reconciliation infrastructure for finance teams, increasingly using AI for reconciliation and risk.',
    profile: {
      problem: 'Finance teams reconcile cash, ledgers, and payments across siloed banks and tools — manual, error-prone, and slow at scale.',
      customer: 'Mid-market finance teams and fintechs moving high transaction volume.',
      aiUseCase: 'ML reconciliation and anomaly detection plus payments operations infrastructure.',
      dataMoatPotential: 'Medium — workflow integration and bank connectivity create switching costs.',
      businessModel: 'Per-transaction and platform fees.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Stripe Treasury, traditional treasury management systems, and ERP-native AP/AR.',
      risks: ['Stripe and other platform competition', 'Bank API reliability dependencies', 'Long enterprise procurement'],
    },
  },
  {
    name: 'Forta',
    sector: 'Healthcare',
    workflowCategory: 'Care Delivery',
    stage: 'Series A',
    geography: 'United States',
    website: 'https://www.fortahealth.com',
    description: 'Forta uses AI-enabled training and supervision to scale parent-led ABA therapy for families with autistic children.',
    profile: {
      problem: 'Demand for ABA therapy far exceeds supply of clinicians, leaving long waitlists and uneven outcomes for autistic children.',
      customer: 'Families with autistic children, primarily in network with payers.',
      aiUseCase: 'AI-driven clinical training plus supervision tooling that scales clinician oversight of parent-led therapy.',
      dataMoatPotential: 'Medium-High — clinical outcomes data and AI training playbooks create defensibility.',
      businessModel: 'In-network reimbursement from payers per session.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with traditional ABA provider networks and digital therapeutic startups.',
      risks: ['Reimbursement variability across payers', 'Clinical efficacy must beat in-person ABA', 'State licensure complexity'],
    },
  },
  {
    name: 'Casetext (CoCounsel)',
    sector: 'Financial Services',
    workflowCategory: 'Legal Automation',
    stage: 'Acquired',
    geography: 'United States',
    website: 'https://casetext.com',
    description: 'Casetext (now part of Thomson Reuters) built CoCounsel, an AI legal assistant for contract review, deposition prep, and case analysis used by law firms and corporate legal.',
    profile: {
      problem: 'Legal work is high-cost knowledge labor — contract review, deposition prep, and case research consume associate time.',
      customer: 'Law firms and corporate legal departments.',
      aiUseCase: 'LLM-driven legal research, contract analysis, and deposition prep grounded in legal corpus.',
      dataMoatPotential: 'Medium — legal corpus access and legal-specific prompt engineering.',
      businessModel: 'Per-seat enterprise SaaS (now via Thomson Reuters).',
      fundingStage: 'Acquired by Thomson Reuters ($650M)',
      competitiveLandscape: 'Now part of TR, competing with Harvey, LexisNexis, and emerging law-firm-specific AI startups.',
      risks: ['Integrated within a large incumbent', 'Heavy hyperscaler and AI startup competition', 'Customer adoption rate uncertain'],
    },
  },
  {
    name: 'Memora Health',
    sector: 'Healthcare',
    workflowCategory: 'Patient Engagement',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.memorahealth.com',
    description: 'Memora Health automates patient-facing care journeys — chronic disease management, post-discharge, and oncology — through SMS and AI agents.',
    profile: {
      problem: 'Health systems cannot scale longitudinal patient care management without overwhelming clinical labor.',
      customer: 'Health systems and large medical groups managing chronic and post-acute populations.',
      aiUseCase: 'Conversational AI care journeys across SMS and voice with clinical-team escalation triggers.',
      dataMoatPotential: 'Medium-High — care journey content library and clinical outcomes data create defensibility.',
      businessModel: 'Per-patient enrolled per month plus enterprise platform fees.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Hippocratic AI, Notable, Memora is more text-first vs. voice.',
      risks: ['Health system sales cycles', 'Patient engagement rates plateau over time', 'Competition from EHR-native MyChart messaging'],
    },
  },
  {
    name: 'Greenhill Bio',
    sector: 'Life Sciences',
    workflowCategory: 'Clinical Operations',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.greenhillbio.com',
    description: 'Greenhill Bio builds AI tools for clinical trial operations — protocol authoring, monitoring report drafting, and CRO oversight.',
    profile: {
      problem: 'Clinical trial operations is paperwork-heavy: protocols, monitoring reports, and CRO oversight all consume scarce ops time.',
      customer: 'Small-to-mid biotech sponsors running 1-5 active trials.',
      aiUseCase: 'AI agents drafting protocols, monitoring reports, and oversight workflows from trial data and prior templates.',
      dataMoatPotential: 'Medium — sponsor-tuned templates and protocol corpora create switching costs.',
      businessModel: 'Per-trial subscription plus professional services.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with Medidata, Veeva, and emerging trial-ops startups.',
      risks: ['Pharma adoption of AI in regulated trial ops is conservative', 'Small initial ICP', 'Validation expectations from sponsors'],
    },
  },
  {
    name: 'Charta Health',
    sector: 'Healthcare',
    workflowCategory: 'Revenue Cycle',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.chartahealth.com',
    description: 'Charta Health uses AI to audit clinical documentation against billing codes, identifying revenue leakage and compliance risk for medical groups.',
    profile: {
      problem: 'Medical groups undercode and overcode visits relative to documentation — leaving money on the table or creating audit exposure.',
      customer: 'Multi-specialty medical groups and management services organizations.',
      aiUseCase: 'LLM-driven audit of clinical notes against billed codes with explanation and revenue uplift recommendations.',
      dataMoatPotential: 'Medium-High — coding compliance models and customer-specific tuning.',
      businessModel: 'Per-encounter or percentage-of-recovered-revenue pricing.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with traditional coding audit vendors and emerging AI RCM startups.',
      risks: ['Coding decisions carry compliance liability', 'Revenue model must beat status quo audit consultancies', 'Coding rules vary widely by payer'],
    },
  },
  {
    name: 'OpenAI Health Concepts',
    sector: 'Healthcare',
    workflowCategory: 'General Platform',
    stage: 'Private',
    geography: 'United States',
    website: 'https://openai.com',
    description: 'OpenAI partnerships with health systems and pharma signal an emerging healthcare AI platform layer; included as a competitive reference.',
    profile: {
      problem: 'Healthcare organizations want general-purpose AI capabilities embedded in HIPAA-compliant infrastructure.',
      customer: 'Health systems and pharma R&D groups.',
      aiUseCase: 'General-purpose LLM API plus HIPAA-compliant deployments for downstream healthcare apps.',
      dataMoatPotential: 'Medium — foundation model depth but limited healthcare-specific data.',
      businessModel: 'Enterprise API and licensing.',
      fundingStage: 'Private (highly capitalized)',
      competitiveLandscape: 'Competes with Anthropic, Google DeepMind, healthcare-vertical LLM vendors.',
      risks: ['Healthcare regulatory complexity', 'Hyperscaler competition', 'Vertical-specific accuracy bar'],
    },
  },
  {
    name: 'Truveta',
    sector: 'Life Sciences',
    workflowCategory: 'Real-World Data',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.truveta.com',
    description: 'Truveta aggregates de-identified clinical data from a consortium of US health systems for pharma research and AI model training.',
    profile: {
      problem: 'Pharma R&D, AI model training, and clinical research lack scaled access to multi-system de-identified clinical data.',
      customer: 'Pharma R&D, health systems, and academic research groups.',
      aiUseCase: 'Data aggregation, normalization, and ML over de-identified longitudinal patient records.',
      dataMoatPotential: 'High — consortium-exclusive multi-system data is hard to replicate.',
      businessModel: 'Data licensing and platform subscription.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Tempus, Flatiron, Owkin, and Optum.',
      risks: ['Data partner concentration', 'Privacy regulation evolution', 'Pharma sales cycles'],
    },
  },
  {
    name: 'EvenUp',
    sector: 'Financial Services',
    workflowCategory: 'Legal Automation',
    stage: 'Series D',
    geography: 'United States',
    website: 'https://www.evenuplaw.com',
    description: 'EvenUp builds AI tools for personal injury law firms — drafting demand letters, organizing medical records, and forecasting case value.',
    profile: {
      problem: 'Personal injury law firms manually review thousands of medical records per case to draft demand letters — slow, expensive, inconsistent.',
      customer: 'Personal injury law firms in the US.',
      aiUseCase: 'AI for medical record review, demand letter drafting, and case value estimation.',
      dataMoatPotential: 'High — proprietary case outcome and demand letter dataset compounds with usage.',
      businessModel: 'Per-case or per-demand-letter pricing.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Niche; competes with traditional legal vendors and emerging law-firm AI tools.',
      risks: ['PI law market concentration risk', 'Regulatory changes around AI in legal practice', 'Customer concentration with large PI firms'],
    },
  },
  {
    name: 'Garner Health',
    sector: 'Healthcare',
    workflowCategory: 'Care Navigation',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://www.garnerhealth.com',
    description: 'Garner Health analyzes employer health claims data and ML quality models to steer members toward higher-quality providers.',
    profile: {
      problem: 'Employers and members cannot identify high-quality providers; quality varies enormously even within networks.',
      customer: 'Self-insured employers and their TPA partners.',
      aiUseCase: 'ML provider quality models trained on multi-billion-row claims dataset for personalized provider matching.',
      dataMoatPotential: 'High — proprietary claims model and employer-specific data.',
      businessModel: 'PMPM (per-member-per-month) employer pricing.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Embold Health, Castlight (legacy), and large carriers.',
      risks: ['Employer benefits sales are cyclical', 'Carrier and broker channel pressure', 'Network steering can face provider pushback'],
    },
  },
];

const Q3_2026: CorpusCompany[] = [
  {
    name: 'Isomorphic Labs',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Late Private',
    geography: 'United Kingdom',
    website: 'https://www.isomorphiclabs.com',
    description: 'Isomorphic Labs is the Alphabet drug discovery company building on DeepMind AlphaFold and structural biology to design and validate small molecules.',
    profile: {
      problem: 'Drug discovery is bottlenecked by protein structure understanding and rational molecule design — areas where deep learning has changed the game.',
      customer: 'Pharma R&D partners and internal pipeline.',
      aiUseCase: 'AlphaFold-derived structural prediction plus generative chemistry tightly integrated with wet lab and partnerships.',
      dataMoatPotential: 'High — DeepMind heritage, proprietary models, and Alphabet capital backing.',
      businessModel: 'Pharma partnership upfronts and milestones plus equity-style co-development.',
      fundingStage: 'Late private (Alphabet-backed)',
      competitiveLandscape: 'Competes with Recursion, Insilico, Schrödinger, and Iambic.',
      risks: ['Clinical asset risk', 'Pharma deal cycles long', 'Internal Alphabet strategic shifts'],
    },
  },
  {
    name: 'BenevolentAI',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Public',
    geography: 'United Kingdom',
    website: 'https://www.benevolent.com',
    description: 'BenevolentAI applies AI to drug discovery — identifying targets and repurposing molecules — with clinical-stage assets in immunology and neuroscience.',
    profile: {
      problem: 'Drug R&D pipelines are slow and high-failure; AI-driven target identification and molecule repurposing can compress cycles.',
      customer: 'Pharma partners and internal pipeline.',
      aiUseCase: 'Knowledge graph + ML platform for target identification, repurposing, and molecule prioritization.',
      dataMoatPotential: 'Medium-High — proprietary knowledge graph and target validation data.',
      businessModel: 'Pharma partnerships plus internal pipeline value capture.',
      fundingStage: 'Public (London Stock Exchange)',
      competitiveLandscape: 'Competes with Recursion, Insilico, Owkin.',
      risks: ['Public market pressure on burn rate', 'Pipeline asset risk', 'Macro pharma R&D budget cycles'],
    },
  },
  {
    name: 'Ramp',
    sector: 'Financial Services',
    workflowCategory: 'Spend Management',
    stage: 'Series D',
    geography: 'United States',
    website: 'https://ramp.com',
    description: 'Ramp combines a corporate card, expense management, and AI-driven spend automation for SMBs and mid-market companies.',
    profile: {
      problem: 'SMB finance teams spend hours on expense management, vendor onboarding, and procurement — manual work AI can automate.',
      customer: 'SMB and mid-market finance teams.',
      aiUseCase: 'AI for expense classification, vendor due diligence, contract review, and procurement automation.',
      dataMoatPotential: 'High — proprietary transaction and vendor dataset compounds with usage.',
      businessModel: 'Interchange revenue plus SaaS subscription tiers.',
      fundingStage: 'Series D',
      competitiveLandscape: 'Competes with Brex, Mercury, Bill.com, and Concur.',
      risks: ['Interchange-dependent revenue volatility', 'Mid-market sales motion', 'AI features increasingly commoditized'],
    },
  },
  {
    name: 'Innovaccer',
    sector: 'Healthcare',
    workflowCategory: 'Population Health',
    stage: 'Series E',
    geography: 'United States',
    website: 'https://innovaccer.com',
    description: 'Innovaccer is a health-cloud and AI platform for population health, value-based care, and clinical workflow analytics.',
    profile: {
      problem: 'Health systems lack a unified data and AI layer for value-based care, care management, and clinical analytics.',
      customer: 'Health systems and large medical groups in value-based contracts.',
      aiUseCase: 'Health cloud aggregating clinical and claims data with AI for risk stratification, care gap identification, and workflow automation.',
      dataMoatPotential: 'High — broad data integration depth across health systems.',
      businessModel: 'Enterprise SaaS plus value-based care PMPM.',
      fundingStage: 'Series E (late-stage)',
      competitiveLandscape: 'Competes with Arcadia, Health Catalyst, Cotiviti.',
      risks: ['Large enterprise sales cycles', 'Margin pressure from health system budgets', 'Crowded population health vendor space'],
    },
  },
  {
    name: 'Saronic',
    sector: 'Cross-Sector',
    workflowCategory: 'Defense AI',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://saronic.com',
    description: 'Saronic builds autonomous surface vessels and AI software for naval and maritime defense applications — included as a Vertical AI reference.',
    profile: {
      problem: 'Naval forces face force projection and patrol gaps that autonomous unmanned vessels can fill at lower cost.',
      customer: 'US Navy and allied defense agencies.',
      aiUseCase: 'AI software for autonomous navigation, mission planning, and sensor fusion on unmanned surface vessels.',
      dataMoatPotential: 'High — defense data and integration relationships are hard to replicate.',
      businessModel: 'Defense contracts and platform sales.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Anduril (maritime), Saildrone, and traditional defense primes.',
      risks: ['Defense procurement cycles', 'Concentration with US DoD as primary customer', 'Geopolitical timing dependencies'],
    },
  },
  {
    name: 'Latent Bio',
    sector: 'Life Sciences',
    workflowCategory: 'Diagnostics',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.latent.bio',
    description: 'Latent Bio builds AI models for pathology image analysis and pharma R&D, focused on rare disease subgroups.',
    profile: {
      problem: 'Rare disease pathology requires highly specialized expertise; AI can scale pattern recognition across distributed pathologists.',
      customer: 'Pharma R&D groups and reference labs in rare disease.',
      aiUseCase: 'Deep learning on pathology whole slide images focused on rare-disease subgroup detection.',
      dataMoatPotential: 'Medium-High — rare-disease annotated pathology datasets and academic partnerships.',
      businessModel: 'Pharma R&D services contracts plus per-slide pricing.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with PathAI, Paige, and academic AI groups.',
      risks: ['Niche initial market', 'Long sales cycles in pharma rare disease', 'Wet lab validation expectations'],
    },
  },
  {
    name: 'Decagon',
    sector: 'Cross-Sector',
    workflowCategory: 'Customer Support AI',
    stage: 'Series C',
    geography: 'United States',
    website: 'https://decagon.ai',
    description: 'Decagon builds enterprise agentic AI for customer support across financial services, healthcare, and consumer brands.',
    profile: {
      problem: 'Enterprises spend billions on customer support labor; agentic AI can resolve a majority of tickets when properly grounded.',
      customer: 'Enterprises in financial services, healthcare, and consumer.',
      aiUseCase: 'Agentic AI for end-to-end ticket resolution including system actions, with guardrails and supervisor workflows.',
      dataMoatPotential: 'Medium-High — customer-specific knowledge bases and intent taxonomies create switching costs.',
      businessModel: 'Per-resolution pricing plus enterprise platform fees.',
      fundingStage: 'Series C',
      competitiveLandscape: 'Competes with Sierra, Salesforce Agentforce, Intercom Fin.',
      risks: ['Hyperscaler competition (Salesforce, Microsoft)', 'Customer ROI proof at scale', 'AI hallucination risk in regulated industries'],
    },
  },
  {
    name: 'Bloom Tracker',
    sector: 'Healthcare',
    workflowCategory: 'Care Delivery',
    stage: 'Series A',
    geography: 'United States',
    website: 'https://www.bloomtracker.com',
    description: 'Bloom Tracker provides AI-enabled remote patient monitoring for prenatal and postpartum care, used by health systems and OB-GYN groups.',
    profile: {
      problem: 'Prenatal and postpartum complications are a leading cause of US maternal mortality; remote monitoring can extend clinical oversight.',
      customer: 'Health systems and OB-GYN practices managing prenatal cohorts.',
      aiUseCase: 'AI-driven risk stratification from RPM device data plus conversational AI patient outreach.',
      dataMoatPotential: 'Medium-High — prenatal RPM dataset and clinical outcome models.',
      businessModel: 'PMPM reimbursement plus health system contracts.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with Maven Clinic (employer-side), Carrot, and traditional RPM vendors.',
      risks: ['Reimbursement variability for RPM', 'OB-GYN practice consolidation', 'Patient adherence to RPM devices'],
    },
  },
  {
    name: 'ZestyAI',
    sector: 'Financial Services',
    workflowCategory: 'Insurance Underwriting',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.zesty.ai',
    description: 'ZestyAI uses computer vision on aerial imagery and ML risk models for property insurance underwriting — wildfire, hail, and roof condition.',
    profile: {
      problem: 'Property insurance underwriting on legacy data leads to mispricing and loss exposure in climate-stressed markets.',
      customer: 'Property insurance carriers and reinsurers.',
      aiUseCase: 'Computer vision on aerial imagery plus ML risk models for property-specific underwriting.',
      dataMoatPotential: 'High — proprietary imagery dataset and risk model calibration.',
      businessModel: 'Per-property pricing plus carrier platform subscriptions.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with CoreLogic, Cape Analytics, and Verisk.',
      risks: ['Climate volatility and regulatory pushback on rate increases', 'Carrier procurement cycles', 'Imagery data partner concentration'],
    },
  },
  {
    name: 'Genesis Therapeutics',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.genesistherapeutics.ai',
    description: 'Genesis Therapeutics applies dynamic molecular dynamics and deep learning to small molecule drug discovery, with pharma partnerships.',
    profile: {
      problem: 'Drug-likeness prediction at scale is difficult without high-quality dynamics modeling integrated into discovery.',
      customer: 'Pharma R&D partners and internal pipeline.',
      aiUseCase: 'Molecular dynamics + ML platform for small molecule discovery.',
      dataMoatPotential: 'Medium-High — proprietary dynamics models plus partner-derived chemistry data.',
      businessModel: 'Pharma partnership upfronts and milestones.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Isomorphic, Recursion, Insilico, Iambic.',
      risks: ['Clinical validation timeline long', 'Pharma deal lumpiness', 'Capital intensity'],
    },
  },
  {
    name: 'Datavant',
    sector: 'Healthcare',
    workflowCategory: 'Health Data Exchange',
    stage: 'Private (Late)',
    geography: 'United States',
    website: 'https://datavant.com',
    description: 'Datavant connects fragmented healthcare data through tokenization and privacy-preserving exchange — foundational infrastructure for healthcare AI.',
    profile: {
      problem: 'Healthcare data is siloed across providers, payers, labs, and pharmas; analytics and AI cannot scale without secure linkage.',
      customer: 'Pharma R&D, payers, providers, and health data analytics partners.',
      aiUseCase: 'Tokenization and privacy-preserving record linkage enabling downstream AI and analytics.',
      dataMoatPotential: 'Very High — network effects across the largest healthcare data exchange in the US.',
      businessModel: 'Platform and transaction-based pricing.',
      fundingStage: 'Late private (post-merger with Ciox)',
      competitiveLandscape: 'Competes with Truveta, IQVIA, and Optum.',
      risks: ['Regulatory shifts in healthcare data exchange', 'Customer concentration with large pharma and payers', 'Privacy and consent landscape evolving'],
    },
  },
  {
    name: 'Sieve Health',
    sector: 'Healthcare',
    workflowCategory: 'Clinical Operations',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.sievehealth.com',
    description: 'Sieve Health uses AI to match patients to clinical trials by parsing EHR data and trial eligibility criteria at scale.',
    profile: {
      problem: 'Clinical trial recruitment is the #1 driver of trial delays; eligibility matching at scale is manual and slow.',
      customer: 'Pharma sponsors, CROs, and academic medical centers.',
      aiUseCase: 'LLM-driven trial-patient matching against EHR data with structured eligibility extraction.',
      dataMoatPotential: 'Medium-High — eligibility extraction patterns and health system relationships.',
      businessModel: 'Per-matched-patient pricing plus enterprise contracts.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with Deep 6 AI, TriNetX, and academic trial matching tools.',
      risks: ['Long pharma sales cycles', 'EHR data access varies by health system', 'Clinical validation expectations'],
    },
  },
  {
    name: 'Anrok',
    sector: 'Financial Services',
    workflowCategory: 'Tax Compliance',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.anrok.com',
    description: 'Anrok automates sales tax compliance for SaaS companies — calculating, filing, and remitting tax across US states and global jurisdictions.',
    profile: {
      problem: 'SaaS companies face fragmented sales tax obligations across thousands of jurisdictions; manual compliance is expensive and error-prone.',
      customer: 'SaaS companies from early-stage through enterprise.',
      aiUseCase: 'ML for jurisdiction classification, tax filing automation, and audit support.',
      dataMoatPotential: 'Medium — jurisdiction rules dataset and customer workflow lock-in.',
      businessModel: 'Annual SaaS subscription tiered by revenue.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Avalara, TaxJar (Stripe), Vertex.',
      risks: ['Avalara/Stripe incumbents bundle pricing', 'Tax rule complexity creates accuracy liability', 'SaaS budget tightening'],
    },
  },
  {
    name: 'Pearl Health',
    sector: 'Healthcare',
    workflowCategory: 'Value-Based Care',
    stage: 'Series B',
    geography: 'United States',
    website: 'https://www.pearlhealth.com',
    description: 'Pearl Health enables independent primary care practices to succeed in Medicare value-based care contracts via AI-driven panel management.',
    profile: {
      problem: 'Independent PCPs cannot operationalize value-based care without enabling technology and capital partnership.',
      customer: 'Independent primary care practices in Medicare Advantage and direct-contracting models.',
      aiUseCase: 'Risk stratification, care gap identification, and panel management tooling driven by claims and clinical data.',
      dataMoatPotential: 'High — outcomes data across value-based contracts compounds with usage.',
      businessModel: 'Per-attributed-patient PMPM plus shared-savings participation.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Aledade, Privia Health, agilon health.',
      risks: ['CMS rate volatility', 'PCP panel concentration risk', 'Capital intensive partnership model'],
    },
  },
  {
    name: 'Vouched',
    sector: 'Financial Services',
    workflowCategory: 'KYC',
    stage: 'Series A',
    geography: 'United States',
    website: 'https://www.vouched.id',
    description: 'Vouched provides identity verification and KYC for fintechs and healthcare, including telehealth provider verification.',
    profile: {
      problem: 'Fintechs and telehealth providers need fast, accurate identity verification across consumer and clinician personas.',
      customer: 'Fintechs, telehealth platforms, and gig marketplaces.',
      aiUseCase: 'Document, biometric, and ML risk verification with industry-specific KYC flows.',
      dataMoatPotential: 'Medium — vertical-specific KYC integrations and partner-tuned models.',
      businessModel: 'Per-verification pricing.',
      fundingStage: 'Series A',
      competitiveLandscape: 'Competes with Persona, Stripe Identity, Alloy, Socure.',
      risks: ['Crowded ID-verification market', 'Margin pressure from upstream data', 'Customer concentration in healthcare/fintech'],
    },
  },
  {
    name: 'Cradle',
    sector: 'Life Sciences',
    workflowCategory: 'Drug Discovery',
    stage: 'Series B',
    geography: 'Netherlands',
    website: 'https://www.cradle.bio',
    description: 'Cradle builds protein design tools for biotech R&D using generative ML, enabling rapid iteration on engineered proteins.',
    profile: {
      problem: 'Protein engineering is iterative and slow; generative ML can dramatically compress design-build-test cycles.',
      customer: 'Biotech R&D teams designing engineered proteins and antibodies.',
      aiUseCase: 'Generative protein design plus closed-loop wet-lab feedback for engineered proteins.',
      dataMoatPotential: 'Medium-High — wet-lab feedback data flywheel within customer engagements.',
      businessModel: 'Per-seat SaaS plus per-project pricing.',
      fundingStage: 'Series B',
      competitiveLandscape: 'Competes with Generate Biomedicines, Isomorphic, and academic protein design tools.',
      risks: ['Biotech R&D budget volatility', 'Long validation cycles for engineered proteins', 'Hyperscaler protein model competition'],
    },
  },
  {
    name: 'Atticus',
    sector: 'Financial Services',
    workflowCategory: 'Legal Automation',
    stage: 'Seed',
    geography: 'United States',
    website: 'https://www.atticus.ai',
    description: 'Atticus uses AI to review and negotiate commercial contracts at scale — focused on SaaS, vendor, and procurement agreements.',
    profile: {
      problem: 'In-house legal teams cannot keep pace with contract volume; commercial deal review is highly templated and AI-suitable.',
      customer: 'In-house legal and procurement teams at mid-to-large enterprises.',
      aiUseCase: 'AI contract review and negotiation playbooks grounded in customer-specific clause libraries.',
      dataMoatPotential: 'Medium-High — customer-specific playbook tuning and clause libraries.',
      businessModel: 'Per-seat enterprise SaaS plus per-contract usage pricing.',
      fundingStage: 'Seed',
      competitiveLandscape: 'Competes with Ironclad AI, Harvey, SpotDraft, and emerging contract AI startups.',
      risks: ['Crowded contract automation space', 'Enterprise legal procurement is conservative', 'LLM commoditization'],
    },
  },
];

export const CORPORA: Corpus[] = [
  {
    id: 'q1-2026',
    label: 'Q1 2026 Pull',
    description: 'Vertical AI companies surfaced in Q1 2026, across healthcare, life sciences, and financial services. Mix of early- and growth-stage names.',
    companies: Q1_2026,
  },
  {
    id: 'q2-2026',
    label: 'Q2 2026 Pull',
    description: 'Spring 2026 sweep emphasizing recently funded and emerging Vertical AI businesses, including some cross-sector AI infrastructure plays.',
    companies: Q2_2026,
  },
  {
    id: 'q3-2026',
    label: 'Q3 2026 Pull',
    description: 'Summer 2026 surface — broader market view including later-stage scaleups and recent breakout companies.',
    companies: Q3_2026,
  },
];

export function getCorpusById(id: string): Corpus | undefined {
  return CORPORA.find((c) => c.id === id);
}
